Simplify project's CI pipeline
- Remove all the custom code for triggering child pipelines
in favor of the, now included in Gitlab free tier, trigger keyword.

- Use matrix to define the images building.

- Child pipeline directly include the yaml so there's no need to detect
  when it's parent or child ($IS_A_CHILD_PIPELINE).

- Remove i386 base dockerfile. It was the same as the amd64. Add the
  namespace logic to `.build_template`

Signed-off-by: Iñaki Malerba <inaki@malerba.space>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -3,10 +3,7 @@
 # Copying and distribution of this file, with or without modification, are
 # permitted in any medium without royalty provided the copyright notice and
 # this notice are preserved. This file is offered as-is, without any warranty.
-include:
- - .pipeline-test.yml
- - .images-debian.yml
-
+---
 workflow:
   rules:
     # Avoid duplicated pipelines, do not run dettached pipelines.
@@ -17,16 +14,79 @@ workflow:
 variables:
   DOCKER_TLS_CERTDIR: ""
   SALSA_CI_DISABLE_APTLY: "false"
+  RELEASE: sid
 
 stages:
   - images
-
-  # From the tested pipeline.
-  - provisioning
-  - build
-  - publish
   - test
-  # End From the tested pipeline.
-
-  - deploy
   - clean
+
+images:
+  stage: images
+  trigger:
+    include:
+      - local: .images-debian.yml
+    strategy: depend
+
+check license + contributor:
+  stage: test
+  image: ${CI_REGISTRY_IMAGE}/base:latest
+  dependencies: []
+  before_script:
+    - apt-get update && apt-get install -y licensecheck
+  script:
+    - PROBLEMS=0
+    # check files without any license
+    - BAD_FILES=$(licensecheck -r . | grep -Ev '(images/files)|(images/patches)|(README.md)|(CONTRIBUTORS)' | grep UNKNOWN) || true
+    - |
+        [ -z "$BAD_FILES" ] || \
+        (echo "ERROR: Missing license statement in the following files:"; \
+         echo "$BAD_FILES"; exit 1) || \
+        PROBLEMS=$(($PROBLEMS + 1))
+    # check email or name is in the list of contributors
+    - |
+        grep -q "${GITLAB_USER_EMAIL}" CONTRIBUTORS || \
+        grep -q "${GITLAB_USER_NAME}" CONTRIBUTORS || \
+        (echo "ERROR: ${GITLAB_USER_NAME} <${GITLAB_USER_EMAIL}> missing in the CONTRIBUTORS file"; exit 1) || \
+        PROBLEMS=$(($PROBLEMS + 1))
+    - exit $PROBLEMS
+
+test-pipeline:
+  trigger:
+    include:
+      - local: .pipeline-test.yml
+    strategy: depend
+  rules:
+    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
+      variables:
+        IMAGE_VERSION: latest
+    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
+      variables:
+        IMAGE_VERSION: ${RELEASE}_${CI_COMMIT_REF_NAME}
+
+clean images:
+  stage: clean
+  image: docker:latest
+  services:
+    - docker:19.03.5-dind
+  variables:
+    IMAGES_LIST: 'aptly autopkgtest base i386/base blhc gbp piuparts reprotest lintian generic_tests'
+  before_script:
+    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
+    - wget -O /usr/bin/reg https://github.com/genuinetools/reg/releases/download/v0.13.0/reg-linux-amd64
+    - chmod +x /usr/bin/reg
+  script:
+    - |
+        # If not master, use REF as staging tag.
+        if ! [ "${CI_COMMIT_REF_NAME}" = "master" ]; then
+          STAGING_TAG="_${CI_COMMIT_REF_NAME}"
+        fi
+    - |
+        for IMAGE in $IMAGES_LIST; do
+          reg --registry ${CI_REGISTRY} rm ${CI_PROJECT_PATH}/${IMAGE}:${RELEASE}${STAGING_TAG} || true
+        done
+  when: always
+  except:
+    variables:
+      - $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
+      - $SALSA_CI_PERSIST_IMAGES =~ /^(1|yes|true)$/
