simplify extract source definition

diff --git a/salsa-ci.yml b/salsa-ci.yml
--- a/salsa-ci.yml
+++ b/salsa-ci.yml
@@ -58,6 +58,55 @@ stages:
   artifacts:
     <<: *artifacts
 
+.provisioning-extract-source: &provisioning-extract-source
+  stage: provisioning
+  image: $SALSA_CI_IMAGES_GBP
+  extends:
+    - .artifacts-default-expire
+  variables:
+    DB_BUILD_PARAM: ${SALSA_CI_DPKG_BUILDPACKAGE_ARGS}
+  except:
+    variables:
+      - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
+  script:
+    - |
+      mkdir -p ${WORKING_DIR}
+
+      gbp pull --ignore-branch --pristine-tar --track-missing
+
+      # Check if we can obtain the orig from the git branches
+      if ! gbp export-orig --tarball-dir=${WORKING_DIR}; then
+        # Fallback using origtargz
+        origtargz -dt
+        cp ../*orig.tar* ${WORKING_DIR}
+        SALSA_CI_GBP_BUILDPACKAGE_ARGS="--git-overlay ${SALSA_CI_GBP_BUILDPACKAGE_ARGS}"
+      fi
+
+      # As of 2020-09-09, gbp doesn't have a simpler method to extract the
+      # debianized source package. Use --git-pbuilder=`/bin/true` for the moment:
+      # https://bugs.debian.org/969952
+      gbp buildpackage \
+           --git-ignore-branch \
+           --git-ignore-new \
+           --git-no-create-orig \
+           --git-export-dir=${WORKING_DIR} \
+           --no-check-builddeps \
+           --git-builder=/bin/true \
+           --git-no-pbuilder \
+           --git-no-hooks \
+           --git-no-purge \
+           ${SALSA_CI_GBP_BUILDPACKAGE_ARGS} |& filter-output
+
+      cd ${WORKING_DIR}
+      DEBIANIZED_SOURCE=$(find . -maxdepth 3 -wholename "*/debian/changelog" |\
+                          awk -F '/debian' '{print $1}')
+      if [ ! "${DEBIANIZED_SOURCE}" ] ; then
+        echo "Error: No valid debianized source tree found."
+        exit 1
+      fi
+
+      mv ${DEBIANIZED_SOURCE} ${SOURCE_DIR}
+
 .build-before-script: &build-before-script |
    # Reported in https://salsa.debian.org/salsa-ci-team/pipeline/issues/104,
    # GitLab can only expand variables once. So at the beginning CCACHE_WORK_DIR
@@ -103,60 +152,6 @@ stages:
    rm -rf ${WORKING_DIR}/${SOURCE_DIR}
    ccache -s
 
-.build-script-extract-source: &build-script-extract-source |
-   mkdir -p ${WORKING_DIR}
-
-   gbp pull --ignore-branch --pristine-tar --track-missing
-
-   # Check if we can obtain the orig from the git branches
-   if ! gbp export-orig --tarball-dir=${WORKING_DIR}; then
-     # Fallback using origtargz
-     origtargz -dt
-     cp ../*orig.tar* ${WORKING_DIR}
-     SALSA_CI_GBP_BUILDPACKAGE_ARGS="--git-overlay ${SALSA_CI_GBP_BUILDPACKAGE_ARGS}"
-   fi
-
-   if ! echo "$SALSA_CI_DISABLE_VERSION_BUMP" | grep -qE '^(1|yes|true)$'; then
-     sed -i -e '1 s/)/+salsaci)/' debian/changelog
-     git config user.email "$DEBEMAIL"
-     git config user.name "$DEBFULLNAME"
-     git commit debian/changelog -m "Salsa CI Version bump"
-   fi
-
-   # As of 2020-09-09, gbp doesn't have a simpler method to extract the
-   # debianized source package. Use --git-pbuilder=`/bin/true` for the moment:
-   # https://bugs.debian.org/969952
-   gbp buildpackage \
-        --git-ignore-branch \
-        --git-ignore-new \
-        --git-no-create-orig \
-        --git-export-dir=${WORKING_DIR} \
-        --no-check-builddeps \
-        --git-builder=/bin/true \
-        --git-no-pbuilder \
-        --git-no-hooks \
-        --git-no-purge \
-        ${SALSA_CI_GBP_BUILDPACKAGE_ARGS} |& filter-output
-
-   cd ${WORKING_DIR}
-   DEBIANIZED_SOURCE=$(find . -maxdepth 3 -wholename "*/debian/changelog" |\
-                       awk -F '/debian' '{print $1}')
-   if [ ! "${DEBIANIZED_SOURCE}" ] ; then
-     echo "Error: No valid debianized source tree found."
-     exit 1
-   fi
-
-   mv ${DEBIANIZED_SOURCE} ${SOURCE_DIR}
-
-.definition-extract-source: &definition-extract-source
-  stage: provisioning
-  image: $SALSA_CI_IMAGES_GBP
-  dependencies: []
-  variables:
-    DB_BUILD_PARAM: ${SALSA_CI_DPKG_BUILDPACKAGE_ARGS}
-  script:
-    - *build-script-extract-source
-
 .build-definition: &build-definition
   stage: build
   image: $SALSA_CI_IMAGES_BASE
@@ -174,24 +169,10 @@ stages:
   dependencies:
     - extract-source
 
-.build-extract-source: &build-extract-source
-  extends:
-    - .definition-extract-source
-    - .artifacts-default-expire
-  variables:
-    DB_BUILD_PARAM: "${SALSA_CI_DPKG_BUILDPACKAGE_ARGS}"
-    SALSA_CI_DISABLE_VERSION_BUMP: 1
-  except:
-    variables:
-      - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
-
-
 .build-package: &build-package
   extends:
     - .build-definition
     - .artifacts-default-expire
-  variables:
-    DB_BUILD_PARAM: "${SALSA_CI_DPKG_BUILDPACKAGE_ARGS}"
   except:
     variables:
       - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
